CUT_MODE_CONVENTIONAL = 1
CUT_MODE_CLIMB = 2

ENTRY_STYLE_UNDEFINED = 0
ENTRY_STYLE_PLUNGE = 1
ENTRY_STYLE_RAMP = 2
ENTRY_STYLE_HELICAL = 3

TOOL_TYPE_DRILL = 1
TOOL_TYPE_CENTREDRILL = 2
TOOL_TYPE_ENDMILL = 3
TOOL_TYPE_SLOTCUTTER = 4
TOOL_TYPE_BALLENDMILL = 5
TOOL_TYPE_CHAMFER = 6
TOOL_TYPE_TURNINGTOOL = 7
TOOL_TYPE_TOUCHPROBE = 8
TOOL_TYPE_TOOLLENGTHSWITCH = 9
TOOL_TYPE_EXTRUSION = 10
TOOL_TYPE_TAPTOOL = 11
TOOL_TYPE_UNDEFINED = 12

TOOL_MATERIAL_UNDEFINED = 0
TOOL_MATERIAL_HSS = 1
TOOL_MATERIAL_CARBIDE = 2

EXTRUSION_MATERIAL_UNDEFINED = 0
EXTRUSION_MATERIAL_ABS = 1
EXTRUSION_MATERIAL_PLA = 2
EXTRUSION_MATERIAL_HDPE = 3

ABS_MODE_ABSOLUTE = 1
ABS_MODE_INCREMENTAL = 2

PATH_CONTROL_UNDEFINED = 0
PATH_CONTROL_EXACT_PATH = 1
PATH_CONTROL_EXACT_STOP = 2
PATH_CONTROL_BEST_POSSIBLE_SPEED = 3
