# just a test to demonstrate how backplotting works
# this writes an xml file which HeeksCNC will open, and paste into the program
f = open('nccode.xml', 'wb')
f.write('<?xml version="1.0" ?>\n')
f.write('<HeeksCAD_Document>\n')
f.write('   <nccode>\n')
f.write('       <ncblock>\n')
f.write('           <text col="block">N10</text>\n')
f.write('           <text col="prep">G0</text>\n')
f.write('           <text col="axis">X10</text>\n')
f.write('           <text>F100</text>\n')
f.write('           <lines col="rapid">\n')
f.write('               <p x="0.000000" y="0.000000" z="0.000000" />\n')
f.write('               <p x="10.000000" y="0.000000" z="0.000000" />\n')
f.write('           </lines>\n')
f.write('       </ncblock>\n')
f.write('       <ncblock>\n')
f.write('           <text col="block">N20</text>\n')
f.write('           <text col="prep">G1</text>\n')
f.write('           <text col="axis">X20</text>\n')
f.write('           <text col="axis">Y10</text>\n')
f.write('           <lines col="feed">\n')
f.write('               <p x="10.000000" y="0.000000" z="0.000000" />\n')
f.write('               <p x="20.000000" y="10.000000" z="0.000000" />\n')
f.write('           </lines>\n')
f.write('       </ncblock>\n')
f.write('   </nccode>\n')
f.write('</HeeksCAD_Document>\n')
